routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('Account')->group(function () {
	Route::get('/', function () {
	    return view('Account.index');
	});

	Route::get('/register', function () {
	    return view('Account.register');
	});

	Route::post('/check_user', 'AccountController@login_user');
	Route::post('/register_account', 'AccountController@register_account');

	Route::get('/logout/admin','AccountController@logout_admin')->name('logout.admin');

	Route::get('/logout/user','AccountController@logout_user')->name('logout.user');

	Route::get('/f_password', function(){
	    return view('Account.forgot_password');
	});

	Route::post('/get_email', 'AccountController@get_email');
	Route::post('/load_question', 'AccountController@load_question');
	Route::post('/submit_answer', 'AccountController@submit_answer');
	Route::post('/save_new_pass', 'AccountController@save_new_pass');

});

Route::namespace('Admin')->group(function () {
	Route::middleware(['auth'])->group(function () {
        
		Route::get('/system/settings', 'AdminController@settings')->name('admin.settings');

		Route::get('/admin', 'AdminController@index')->name('admin.index');
		Route::get('/attendance', 'AdminController@attendance')->name('admin.attendance');
		Route::get('/admin/list_attendance/{date_from}/{date_to}', 'AdminController@list_attendance')->name('admin.attendance');
		
		// Crud
		Route::get('/admin/list_employee', 'AdminController@list_employee')->name('employee.list');
		Route::post('/admin/add_employee', 'AdminController@add_employee')->name('employee.add');
		Route::get('/admin/delete_employee/{user_id}', 'adminController@delete_employee')->name('employee.delete');
		
	});
});

Route::namespace('User')->group(function () {
	Route::middleware(['auth'])->group(function () {
		//Route::get('/user', 'UserController@index')->name('user.index');
		Route::get('/user', 'UserController@index');
		Route::post('/user/time_log', 'UserController@time_log')->name('user.time_log');
		Route::post('/user/time_log_button', 'UserController@time_log_button')->name('user.time_log_button');
		Route::get('/user/load_logs_today', 'UserController@load_logs_today')->name('user.attendance');

		Route::get('/user/accountsettings', 'UserController@accountsettings')->name('user.accountsettings');
		Route::post('/user/update_accountsetting', 'UserController@update_accountsetting')->name('user.update_accountsetting');
		// Change Password
		Route::post('/user/changepassword', 'UserController@changepassword')->name('user.changepassword');
		Route::post('/user/add_security_option', 'UserController@add_security_option')->name('employee.add_security_option');
		Route::get('/user/question_counter', 'UserController@question_counter')->name('user.question_counter');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token',
    ];
    
    protected $primaryKey = 'user_id';

    protected $table = 'tbl_users';

    protected $fillable = [
        'profile_picture','firstname', 'lastname', 'middlename', 'password', 'email_address', 'gender', 'birthdate', 'address','country', 'user_type', 'created_at', 'updated_at', 'deleted_at'
    ];

    public function getFullnameAttribute(){
        return $this->firstname.' '.$this->lastname;
    }

    public function setPasswordAttribute($value){
        $this->attributes['password'] = Hash::make($value);
    }

}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Attendance;
use App\User;
use App\UserOption;
use Auth;
use Validator;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('User.index');
    }

    public function time_log(Request $request){

        $userid = auth()->id();
        $date_today = date('Y-m-d');
        $type =  $request->get('type');
        $check_attendance = Attendance::where('user_id', $userid)->where('date_trans',$date_today)->get();
        $row = $check_attendance->first();
        if($type == 'time_in_f'){
            $lbl = "Time in First";
            $log_status = "You already stored your Time In A.M.";
        }elseif($type == 'time_out_f'){
            $lbl = "Time Out First";
            $log_status = "You already stored your Time Out A.M.";
        }elseif($type == 'time_in_l'){
            $lbl = "Time In Last";
            $log_status = "You already stored your Time In P.M.";
        }elseif($type == 'time_out_l'){
            $lbl = "Time Out Last";
            $log_status = "You already stored your Time Out P.M.";
        }
        $desc = $lbl.' successfully logged!';

        if($check_attendance->count() > 0){
            //update
            
            if($row->$type <> ''){
                //check if already stored data on specific field
                return response()->json(['status' => false, 'message' => $log_status]);
            }else{
                
                $attendance = Attendance::find($row->id);
                $attendance->date_trans =  $date_today;
                $attendance->date_trans =  $date_today;
                $attendance->$type = date('h:i A');
                $attendance->created_at = date('Y-m-d H:i:s');
                if($attendance->save()){
                    return response()->json(['status' => true, 'message' => $desc]);
                }

            }

        }else{
            //insert
            $attendance = new Attendance;
            $attendance->user_id = $userid;
            $attendance->date_trans =  $date_today;
            $attendance->date_trans =  $date_today;
            $attendance->$type = date('h:i A');
            $attendance->created_at = date('Y-m-d H:i:s');
            if($attendance->save()){
                return response()->json(['status' => true, 'message' => $desc]);
            }

        }

    }

    public function time_log_button(Request $request){

        $time_now = date('H:i');
       // $time_now = '17:00;'
        if($time_now >= '08:00' && $time_now <= '11:59'){
            echo 'time_in_f';
        }elseif($time_now >= '12:00' && $time_now <= '12:59'){
            echo 'time_out_f';
        }elseif($time_now >= '13:00' && $time_now <= '16:59'){
            echo 'time_in_l';
        }elseif($time_now >= '17:00'){
            echo 'time_out_l';
        }else{
            echo 'no_time_log';
        }
    }

    public function load_logs_today(){
        $date_today = date('Y-m-d');
        $userid = auth()->id();
        $attendance = Attendance::where('date_trans', $date_today)->where('user_id', $userid)->whereNull('deleted_at')->get();
		return response()->json(['status' => true, 'data' => $attendance]);
    }

    public function accountsettings(){
        return view('User/accountsettings');
    }

    function update_accountsetting(Request $request){

		$user_id= $request->get('user_id');
		$firstname = $request->get('firstname');
		$lastname = $request->get('lastname');
		$middlename = $request->get('middlename');
		$email_address = $request->get('email_address');
        $gender = $request->get('gender');
		$birthday = $request->get('birthday');
		$address = $request->get('address');
		$country = $request->get('country');

		$validator = Validator::make($request->all(), [
			'firstname' => 'required',
			'lastname' => 'required',
			'middlename' => 'required',
			'email_address' => 'required|email',
		]);

		if ($validator->fails()) {
			return response()->json(['status' => false, 'error' => $validator->errors()]);
		}else{
			if (!empty($user_id)) {
				$employee = User::find($user_id);
				$employee->firstname = $firstname;
				$employee->lastname = $lastname;
				$employee->middlename = $middlename;
				$employee->email_address = $email_address;
                $employee->gender = $gender;
				$employee->birthdate = $birthday;
				$employee->address = $address;
				$employee->country = $country;
				if($employee->save()){
					return response()->json(['status' => true, 'message' => 'Account Settings updated successfully!']);
				}
			}
		}
    }

    function changepassword(Request $request){

        $user_id= $request->get('user_id');
        $currentpassword = $request->get('currentpassword');
        $newpassword = $request->get('newpassword');
        $confirmpassword = $request->get('password_confirmation');

        $validator = Validator::make($request->all(), [
            'currentpassword' => 'required',
            'newpassword' => 'required',
            'password_confirmation' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'error' => $validator->errors()]);
        }
        elseif (!(Hash::check($currentpassword, Auth::user()->password))){
            $validator->errors()->add('currentpassword', 'Your current password does not match with your provided');
            return response()->json(['status' => false, 'error' => $validator->errors()]);
        }
        elseif (strcmp($currentpassword,$newpassword)==0){
            $validator->errors()->add('newpassword', 'Your current password cannot be same with the new password');
            return response()->json(['status' => false, 'error' => $validator->errors()]);
        }
        elseif ($newpassword != $confirmpassword){
            $validator->errors()->add('password_confirmation', 'Confirm Password does not match with your new password');
            return response()->json(['status' => false, 'error' => $validator->errors()]);
        }
        else{
            if (!empty($user_id)) {
                $employee = User::find($user_id);
                $employee->password = $newpassword;
                if($employee->save()){
                    return response()->json(['status' => true, 'message' => 'Password changed successfully']);
                }
            }
        }
    }

    function add_security_option(Request $request){

        $user_id= auth()->id();
		$question = $request->get('question');
        $answer = $request->get('answer');
        $email_address = $request->get('email_address');

        $check_duplicate = UserOption::where('user_id', $user_id)->where('question',$question)->get();
       
        if($check_duplicate->count() > 0){
            return response()->json(['status' => '3', 'message' => 'Question Already exists. Please select other security option.']);
        }else{

            $user_option = new UserOption;
            $user_option->user_id = $user_id;
            $user_option->email_address =  $email_address;
            $user_option->question =  $question;
            $user_option->answer =$answer;
            $user_option->created_at = date('Y-m-d H:i:s');

            if($user_option->save()){
                
                $counter = UserOption::where('user_id', $user_id)->get();
                if($counter->count() > 2){
                    
                    $user_up = User::find($user_id);
                    $user_up->security_options = 1;
                    if($user_up->save()){
                        return response()->json(['status' => '1', 'message' => 'Thank you for you answers.']);
                    }

                }else{
                    return response()->json(['status' => '2', 'message' => 'Successfully saved...']);
                }
                

            }

        }
    
    }

    function question_counter(){
        $user_id= auth()->id();
        $counter = UserOption::where('user_id', $user_id)->get();
        return $counter->count();
    }

}

resources/views/User/accountsettings.blade.php
<!DOCTYPE html>
<html>
  <!-- Header css meta -->
   @include('Layout.header', ['type' => 'user', 'title' => 'Account Settings', 'icon' => asset('img/logo.png') ])
<body class="sidebar-mini layout-fixed">
  <div class="wrapper">
  <!-- navbar -->
  @include('Layout.nav', ['type' => 'user'])
  <!-- Sidebar -->
  @include('Layout.sidebar', ['type' => 'user'])
    <div class="content-wrapper">
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 mt-3">
              <div class="card">
                <div class="card-header bg-light">
                  <div class="card-header h4"><i class="fas fa-cog"></i> <span>Account Settings</span></div>
                </div>
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="card">
                        <div class="card-header bg-light">
                          Profile
                        </div>
                          <ul class="list-group list-group-flush">
                            <li class="list-group-item">Name <span class="float-right">{{ Auth::user()->fullname }}</span></li>
                            <li class="list-group-item">Email <span class="float-right">{{ Auth::user()->email_address }}</span></li>
                            <li class="list-group-item">Date Registered <span class="float-right">{{ \Carbon\Carbon::parse(Auth::user()->created_at)->format('M d, Y')}}</span></li>
                          </ul>
                          
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="card">
                        <div class="card-header bg-light">
                          Account Settings
                        </div>
                        <div class="card-body">
                            <form class="needs-validation" id="update_form_id" action="{{ url('/user/update_accountsetting') }}" novalidate>
                                <div class="form-row">
                                    <input type="hidden" id="user_id" name="user_id" placeholder="" value='{{ Auth::user()->user_id }}' class="form-control" required>
                                    <div class="form-group col-sm-12">
                                        <label>First Name </label>
                                        <input type="text" id="firstname" name="firstname" placeholder="First Name" value='{{ Auth::user()->firstname }}' class="form-control " required>
                                        <div class="invalid-feedback" id="err_firstname"></div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <label>Middle Name </label>
                                        <input type="text" id="middlename" name="middlename" placeholder="Middle Name" value='{{ Auth::user()->middlename }}' class="form-control " required>
                                        <div class="invalid-feedback" id="err_middlename"></div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <label>Last Name </label>
                                        <input type="text" id="lastname" name="lastname" placeholder="Last Name" value='{{ Auth::user()->lastname }}' class="form-control " required>
                                        <div class="invalid-feedback" id="err_lastname"></div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <label>Email </label>
                                        <input type="email" id="email_address" name="email_address" placeholder="Email Address" value='{{ Auth::user()->email_address }}' class="form-control " required>
                                        <div class="invalid-feedback" id="err_email_address"></div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="row">
                                          <div class="form-group col-sm-6">
                                            <label>Gender </label>
                                            <select class="form-control" id="gender" name="gender">
                                                <option value="Female"  @if(Auth::user()->gender == "Female") selected @endif>Female</option>
                                                <option value="Male" @if(Auth::user()->gender == "Male") selected @endif>Male</option>
                                            </select>
                                            <div class="invalid-feedback" id="err_gender"></div>
                                          </div>
                                          <div class="form-group col-sm-6">
                                            <label>Birthday </label>
                                            <input type="date" id="birthday" value="{{ Auth::user()->birthdate }}" name="birthday" placeholder="Birthday" class="form-control " required>
                                            <div class="invalid-feedback" id="err_birthday"></div>
                                          </div>
                                          
                                        </div>
                                      </div>
                                      <div class="col-md-12">
                                        <div class="row">
                                          <div class="form-group col-sm-6">
                                            <label>Address </label>
                                            <input type="text" id="address" value="{{ Auth::user()->address }}" name="address" placeholder="Address" class="form-control " required>
                                            <div class="invalid-feedback" id="err_address"></div>
                                          </div>
                                          <div class="form-group col-sm-6">
                                            <label>Country </label>
                                            <input type="text" id="country" value ="{{ Auth::user()->country }}" name="country" placeholder="Country" class="form-control " required>
                                            <div class="invalid-feedback" id="err_country"></div>
                                          </div>
                                          
                                        </div>
                                      </div>
                                    <div class="col-sm-12 text-right">
                                        <button class="btn btn-secondary" type="submit">Save</button>
                                        <button type="button" class="btn btn-outline-secondary" onclick="change_password()">Change Password</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- Modal Change Password -->
    <div class="modal fade" role="dialog" id="modal_change_password">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-title">
            Change Password
            </div>
            <button class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <form class="needs-validation" id="changepassword_id" action="{{ url('/user/changepassword') }}" novalidate>
              <div class="form-row">
                <input type="hidden" id="user_id" name="user_id" value="{{ Auth::user()->user_id }}" placeholder="" class="form-control" required>
                <div class="form-group col-sm-12">
                  <label>Current Password </label>
                  <input type="password" id="currentpassword" name="currentpassword" placeholder="Current Password" class="form-control " required>
                  <div class="invalid-feedback" id="err_currentpassword"></div>
                </div>
                <div class="form-group col-sm-12">
                  <label>New Password </label>
                  <input type="password" id="newpassword" name="newpassword" placeholder="New Password" class="form-control " required>
                  <div class="invalid-feedback" id="err_newpassword"></div>
                </div>
                <div class="form-group col-sm-12">
                  <label>Confirm Password </label>
                  <input type="password" id="password_confirmation" name="password_confirmation" placeholder="Confirm New Password" class="form-control " required>
                  <div class="invalid-feedback" id="err_password_confirmation"></div>
                </div>

                <div class="col-sm-12 text-right">
                  <button class="btn btn-secondary" type="submit">Save</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>



  </div>
</body>
  <!-- Footer Scripts -->
  @include('Layout.footer', ['type' => 'user'])
</html>

<script>

$("#update_form_id").on('submit', function(e){
		var url = $(this).attr('action');
		var mydata = $(this).serialize();
		e.stopPropagation();
		e.preventDefault(e);

		$.ajax({
			type:"POST",
			url:url,
			data:mydata,
			cache:false,
			beforeSend:function(){
					//<!-- your before success function -->
			},
			success:function(response){
					//console.log(response)
				if(response.status == true){
					console.log(response)
					swal("Success", response.message, "success");
					showValidator(response.error,'update_form_id');
				}else{
					//<!-- your error message or action here! -->
					showValidator(response.error,'update_form_id');
				}
			},
			error:function(error){
				console.log(error)
			}
		});
	});

  // Modal Change Password

  function change_password(){
    $("#modal_change_password").modal('show');
  }

  $("#changepassword_id").on('submit', function(e){
		var url = $(this).attr('action');
		var mydata = $(this).serialize();
		e.stopPropagation();
		e.preventDefault(e);

		$.ajax({
			type:"POST",
			url:url,
			data:mydata,
			cache:false,
			beforeSend:function(){
					//<!-- your before success function -->
			},
			success:function(response){
					//console.log(response)
				if(response.status == true){
					console.log(response)
					swal("Success", response.message, "success");
					showValidator(response.error,'changepassword_id');
          $('#modal_change_password').modal('hide');
          $('body').removeClass('modal-open');
          $('.modal-backdrop').remove();
				}else{
					//<!-- your error message or action here! -->
					showValidator(response.error,'changepassword_id');
				}
			},
			error:function(error){
				console.log(error)
			}
		});
	});



</script>